/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksImport } from './routes/tasks'
import { Route as RegisterImport } from './routes/register'
import { Route as ProductsImport } from './routes/products'
import { Route as LoginImport } from './routes/login'
import { Route as CartImport } from './routes/cart'
import { Route as AboutImport } from './routes/about'
import { Route as notFoundImport } from './routes/__not-found'
import { Route as IndexImport } from './routes/index'
import { Route as ProductProductIdImport } from './routes/product.$productId'

// Create/Update Routes

const TasksRoute = TasksImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProductsRoute = ProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const notFoundRoute = notFoundImport.update({
  id: '/__not-found',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductProductIdRoute = ProductProductIdImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__not-found': {
      id: '/__not-found'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof notFoundImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof notFoundRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/product/$productId': typeof ProductProductIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof notFoundRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/product/$productId': typeof ProductProductIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__not-found': typeof notFoundRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/register': typeof RegisterRoute
  '/tasks': typeof TasksRoute
  '/product/$productId': typeof ProductProductIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/cart'
    | '/login'
    | '/products'
    | '/register'
    | '/tasks'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/cart'
    | '/login'
    | '/products'
    | '/register'
    | '/tasks'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/__not-found'
    | '/about'
    | '/cart'
    | '/login'
    | '/products'
    | '/register'
    | '/tasks'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  notFoundRoute: typeof notFoundRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  RegisterRoute: typeof RegisterRoute
  TasksRoute: typeof TasksRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  notFoundRoute: notFoundRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  RegisterRoute: RegisterRoute,
  TasksRoute: TasksRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__not-found",
        "/about",
        "/cart",
        "/login",
        "/products",
        "/register",
        "/tasks",
        "/product/$productId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__not-found": {
      "filePath": "__not-found.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/products": {
      "filePath": "products.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/tasks": {
      "filePath": "tasks.tsx"
    },
    "/product/$productId": {
      "filePath": "product.$productId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
